### ISSUE TITLE
Getting started with the Web

### ISSUE THREAD

**Issue by trujkich** [trujkich/ppt#1]
>### Getting started with the Web
>Provides a practical introduction to web development for complete beginners.

### Task List
- [ ]  Installing basic software
- [ ] What will your website look like?
- [ ] Dealing with files
- [ ] HTML basics
- [ ] CSS basics
- [ ] JavaScript basics
- [ ] Publishing your website
- [ ] How the Web works
